name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: ./Katha-Sales
        run: npm install
          
      - name: Build
        working-directory: ./Katha-Sales
        run: npm run build
          
      - name: Deploy to Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local-dir: ./Katha-Sales/dist/
          server-dir: /var/www/html/katha-sales/ 