name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: ./Katha-Sales
        run: npm install
          
      - name: Build
        working-directory: ./Katha-Sales
        run: npm run build
          
      - name: Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          local_path: './Katha-Sales/dist/*'
          remote_path: '/var/www/html/katha-sales'
          sftpArgs: '-o StrictHostKeyChecking=no' 