name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: ./Katha-Sales
        run: npm install
          
      - name: Build
        working-directory: ./Katha-Sales
        run: npm run build

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
      - name: Deploy with scp
        run: |
          scp -i ~/.ssh/deploy_key -r ./Katha-Sales/dist/* root@${{ secrets.SERVER_HOST }}:/var/www/html/katha-sales/ 