name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        working-directory: ./Katha-Sales
        run: |
          npm install
          npm install -D @tailwindcss/forms
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p
          
      - name: Build Frontend
        working-directory: ./Katha-Sales
        run: |
          npm run build
        env:
          CI: false

      - name: Setup SSH and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          
          # Install PM2 and create app directory
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "sudo npm install -g pm2 && sudo mkdir -p /var/www/katha-sales && sudo chown -R $SERVER_USERNAME:$SERVER_USERNAME /var/www/katha-sales"
          
          # Deploy frontend and backend
          cd Katha-Sales
          tar -czf ../deploy.tar.gz dist backend package.json
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ../deploy.tar.gz $SERVER_USERNAME@$SERVER_HOST:/var/www/katha-sales/
          
          # Extract and setup on server
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "cd /var/www/katha-sales && tar -xzf deploy.tar.gz && npm install --production && pm2 delete katha-sales || true && pm2 start backend/index.cjs --name katha-sales" 